# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inspo < Formula
  desc "A tool for exploring layers in a docker image"
  homepage "https://github.com/khulnasoft/inspo/"
  version "0.0.0-SNAPSHOT-c4ba151"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/khulnasoft/inspo/releases/download/v0.0.0/inspo_0.0.0-SNAPSHOT-c4ba151_darwin_arm64.tar.gz"
      sha256 "5c3688d3b0bf879f30386181c4102fe2bcaf2ade59a2b184235559b6a5d9ea7f"

      def install
        bin.install "inspo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/khulnasoft/inspo/releases/download/v0.0.0/inspo_0.0.0-SNAPSHOT-c4ba151_darwin_amd64.tar.gz"
      sha256 "9569427e22efe095f70b2c3c7fd9018529a4354dbe4dc7c6a65ed31163b226a0"

      def install
        bin.install "inspo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/khulnasoft/inspo/releases/download/v0.0.0/inspo_0.0.0-SNAPSHOT-c4ba151_linux_amd64.tar.gz"
      sha256 "405794cdd100898616a5d75f5f4795c3adb3035acfbb9343c7881f94c8488193"

      def install
        bin.install "inspo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/khulnasoft/inspo/releases/download/v0.0.0/inspo_0.0.0-SNAPSHOT-c4ba151_linux_arm64.tar.gz"
      sha256 "3f74d5bf706de73c2249179b4c2bb8bd2c7d2c23e7ae5d43e2f0097d31b8e4d9"

      def install
        bin.install "inspo"
      end
    end
  end
end
