# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inspo < Formula
  desc "A tool for exploring layers in a docker image"
  homepage "https://github.com/khulnasoft/inspo/"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/khulnasoft/inspo/releases/download/v0.0.3/inspo_0.0.3_darwin_amd64.tar.gz"
      sha256 "eb10cbf3f0c882ef96524b12a2d9fc8f64b9bd5aee13178778138b78956b5c59"

      def install
        bin.install "inspo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/khulnasoft/inspo/releases/download/v0.0.3/inspo_0.0.3_darwin_arm64.tar.gz"
      sha256 "15ccd520feb0ac3e06409f9d92db8583526542e515871c7a25b47c2ccf18d100"

      def install
        bin.install "inspo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/khulnasoft/inspo/releases/download/v0.0.3/inspo_0.0.3_linux_arm64.tar.gz"
      sha256 "cf7407399c234386822545cd78eec7e25cef09f101ea437cfc3bb6693936530b"

      def install
        bin.install "inspo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/khulnasoft/inspo/releases/download/v0.0.3/inspo_0.0.3_linux_amd64.tar.gz"
      sha256 "1e351f683a256f4ed2dc103a7c40ceb5e7870db7739783d12a5e5502d46301c4"

      def install
        bin.install "inspo"
      end
    end
  end
end
